/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PristifyActionBold {
    }
    interface PristifyActionH1 {
    }
    interface PristifyActionH2 {
    }
    interface PristifyActionItalic {
    }
    interface PristifyActionStrikethrough {
    }
    interface PristifyActionUnderline {
    }
    interface PristifyEditor {
    }
    interface PristifyEditorContent {
    }
    interface PristifyEditorHeader {
    }
    interface PristifyEditorHeaderAction {
        "active": boolean;
        "icon": string;
    }
}
export interface PristifyEditorHeaderActionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPristifyEditorHeaderActionElement;
}
declare global {
    interface HTMLPristifyActionBoldElement extends Components.PristifyActionBold, HTMLStencilElement {
    }
    var HTMLPristifyActionBoldElement: {
        prototype: HTMLPristifyActionBoldElement;
        new (): HTMLPristifyActionBoldElement;
    };
    interface HTMLPristifyActionH1Element extends Components.PristifyActionH1, HTMLStencilElement {
    }
    var HTMLPristifyActionH1Element: {
        prototype: HTMLPristifyActionH1Element;
        new (): HTMLPristifyActionH1Element;
    };
    interface HTMLPristifyActionH2Element extends Components.PristifyActionH2, HTMLStencilElement {
    }
    var HTMLPristifyActionH2Element: {
        prototype: HTMLPristifyActionH2Element;
        new (): HTMLPristifyActionH2Element;
    };
    interface HTMLPristifyActionItalicElement extends Components.PristifyActionItalic, HTMLStencilElement {
    }
    var HTMLPristifyActionItalicElement: {
        prototype: HTMLPristifyActionItalicElement;
        new (): HTMLPristifyActionItalicElement;
    };
    interface HTMLPristifyActionStrikethroughElement extends Components.PristifyActionStrikethrough, HTMLStencilElement {
    }
    var HTMLPristifyActionStrikethroughElement: {
        prototype: HTMLPristifyActionStrikethroughElement;
        new (): HTMLPristifyActionStrikethroughElement;
    };
    interface HTMLPristifyActionUnderlineElement extends Components.PristifyActionUnderline, HTMLStencilElement {
    }
    var HTMLPristifyActionUnderlineElement: {
        prototype: HTMLPristifyActionUnderlineElement;
        new (): HTMLPristifyActionUnderlineElement;
    };
    interface HTMLPristifyEditorElement extends Components.PristifyEditor, HTMLStencilElement {
    }
    var HTMLPristifyEditorElement: {
        prototype: HTMLPristifyEditorElement;
        new (): HTMLPristifyEditorElement;
    };
    interface HTMLPristifyEditorContentElement extends Components.PristifyEditorContent, HTMLStencilElement {
    }
    var HTMLPristifyEditorContentElement: {
        prototype: HTMLPristifyEditorContentElement;
        new (): HTMLPristifyEditorContentElement;
    };
    interface HTMLPristifyEditorHeaderElement extends Components.PristifyEditorHeader, HTMLStencilElement {
    }
    var HTMLPristifyEditorHeaderElement: {
        prototype: HTMLPristifyEditorHeaderElement;
        new (): HTMLPristifyEditorHeaderElement;
    };
    interface HTMLPristifyEditorHeaderActionElement extends Components.PristifyEditorHeaderAction, HTMLStencilElement {
    }
    var HTMLPristifyEditorHeaderActionElement: {
        prototype: HTMLPristifyEditorHeaderActionElement;
        new (): HTMLPristifyEditorHeaderActionElement;
    };
    interface HTMLElementTagNameMap {
        "pristify-action-bold": HTMLPristifyActionBoldElement;
        "pristify-action-h1": HTMLPristifyActionH1Element;
        "pristify-action-h2": HTMLPristifyActionH2Element;
        "pristify-action-italic": HTMLPristifyActionItalicElement;
        "pristify-action-strikethrough": HTMLPristifyActionStrikethroughElement;
        "pristify-action-underline": HTMLPristifyActionUnderlineElement;
        "pristify-editor": HTMLPristifyEditorElement;
        "pristify-editor-content": HTMLPristifyEditorContentElement;
        "pristify-editor-header": HTMLPristifyEditorHeaderElement;
        "pristify-editor-header-action": HTMLPristifyEditorHeaderActionElement;
    }
}
declare namespace LocalJSX {
    interface PristifyActionBold {
    }
    interface PristifyActionH1 {
    }
    interface PristifyActionH2 {
    }
    interface PristifyActionItalic {
    }
    interface PristifyActionStrikethrough {
    }
    interface PristifyActionUnderline {
    }
    interface PristifyEditor {
    }
    interface PristifyEditorContent {
    }
    interface PristifyEditorHeader {
    }
    interface PristifyEditorHeaderAction {
        "active"?: boolean;
        "icon"?: string;
        "onActionClicked"?: (event: PristifyEditorHeaderActionCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "pristify-action-bold": PristifyActionBold;
        "pristify-action-h1": PristifyActionH1;
        "pristify-action-h2": PristifyActionH2;
        "pristify-action-italic": PristifyActionItalic;
        "pristify-action-strikethrough": PristifyActionStrikethrough;
        "pristify-action-underline": PristifyActionUnderline;
        "pristify-editor": PristifyEditor;
        "pristify-editor-content": PristifyEditorContent;
        "pristify-editor-header": PristifyEditorHeader;
        "pristify-editor-header-action": PristifyEditorHeaderAction;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pristify-action-bold": LocalJSX.PristifyActionBold & JSXBase.HTMLAttributes<HTMLPristifyActionBoldElement>;
            "pristify-action-h1": LocalJSX.PristifyActionH1 & JSXBase.HTMLAttributes<HTMLPristifyActionH1Element>;
            "pristify-action-h2": LocalJSX.PristifyActionH2 & JSXBase.HTMLAttributes<HTMLPristifyActionH2Element>;
            "pristify-action-italic": LocalJSX.PristifyActionItalic & JSXBase.HTMLAttributes<HTMLPristifyActionItalicElement>;
            "pristify-action-strikethrough": LocalJSX.PristifyActionStrikethrough & JSXBase.HTMLAttributes<HTMLPristifyActionStrikethroughElement>;
            "pristify-action-underline": LocalJSX.PristifyActionUnderline & JSXBase.HTMLAttributes<HTMLPristifyActionUnderlineElement>;
            "pristify-editor": LocalJSX.PristifyEditor & JSXBase.HTMLAttributes<HTMLPristifyEditorElement>;
            "pristify-editor-content": LocalJSX.PristifyEditorContent & JSXBase.HTMLAttributes<HTMLPristifyEditorContentElement>;
            "pristify-editor-header": LocalJSX.PristifyEditorHeader & JSXBase.HTMLAttributes<HTMLPristifyEditorHeaderElement>;
            "pristify-editor-header-action": LocalJSX.PristifyEditorHeaderAction & JSXBase.HTMLAttributes<HTMLPristifyEditorHeaderActionElement>;
        }
    }
}
